#!/bin/bash

set -e

REVISION=$1

if [[ $ABI == 32 ]]; then
    PYPY_PATH=/opt/pypy-i686/bin
else
    PYPY_PATH=/opt/pypy-x86_64/bin
fi

if [[ $ABI == "32" ]]; then
    export CFLAGS="-m32 $CFLAGS"
    export CPPFLAGS=$CFLAGS
    export LDFLAGS="-m32 $LDFLAGS"
fi

export PATH=/opt/prefix/cpython-2.7/bin:$PYPY_PATH:$PATH

env

rm -rf pypy
mkdir -p pypy
wget https://bitbucket.org/pypy/pypy/get/${REVISION:=default}.tar.bz2 -O - | tar -C pypy --strip-components=1 -xj

wget --no-check-certificate https://pypi.python.org/packages/be/64/1bb257ffb17d01f4a38d7ce686809a736837ad4371bcc5c42ba7a715c3ac/pycparser-2.17.tar.gz -O - | tar xz
mv pycparser-2.17/pycparser pypy

cd pypy
patch -p0 < ../platform_linux.patch
python rpython/bin/rpython -Ojit pypy/goal/targetpypystandalone.py
cd -
