#!/bin/bash

set -e

if [[ $ABI == "32" ]]; then
    export CFLAGS="-m32 $CFLAGS"
    export CPPFLAGS=$CFLAGS
    export LDFLAGS="-m32 $LDFLAGS"
fi

env

rm -rf Python-2.7.11
wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
tar xf Python-2.7.11.tgz

cd Python-2.7.11
./configure --prefix=/opt/prefix/cpython-2.7
make -j4
make install
