#!/bin/bash

set -e

if [[ $ABI == "32" ]]; then
    export CFLAGS="-m32 $CFLAGS"
    export CPPFLAGS=$CFLAGS
    export LDFLAGS="-m32 $LDFLAGS"
fi

env

set -x

wget http://ftp.gnu.org/gnu/ncurses/ncurses-6.0.tar.gz -O - | tar xz
cd ncurses-6.0
./configure --prefix=/opt/prefix --without-cxx --with-termlib --without-normal --with-shared --enable-database --with-terminfo-dirs=/lib/terminfo:/usr/share/terminfo
echo "#define NCURSES_USE_DATABASE 1" >> include/ncurses_cfg.h
make
make install
cd -

wget http://ftp.vim.org/security/openssl/openssl-1.0.2h.tar.gz -O - | tar xz
cd openssl-1.0.2h
if [[ $ABI == "32" ]]; then
    setarch i386 ./config --prefix=/opt/prefix -m32 shared
else
    ./config --prefix=/opt/prefix shared
fi
sed -i "s#^SHARED_LDFLAGS=\\(.*\\)#SHARED_LDFLAGS=$LDFLAGS \\1#" Makefile
make
make install
cd -

wget http://tukaani.org/xz/xz-5.2.2.tar.gz -O - | tar xz
cd xz-5.2.2
./configure --prefix=/opt/prefix
make -j4
make install
cd -

wget http://nixos.org/releases/patchelf/patchelf-0.9/patchelf-0.9.tar.gz -O - | tar xz
cd patchelf-0.9
./configure --prefix=/opt/prefix
make -j4
make install
cd -


wget https://sqlite.org/2016/sqlite-autoconf-3140100.tar.gz -O - | tar xz
cd sqlite-autoconf-3140100
./configure --prefix=/opt/prefix
make -j4
make install
cd -

wget ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz -O - | tar xz
cd libffi-3.2.1
./configure --prefix=/opt/prefix
make -j4
make install
cd -

cd /opt/prefix/lib
find . -name ffi.h | xargs -i ln -sf ../lib/{} ../include
find . -name ffitarget.h | xargs -i ln -sf ../lib/{} ../include
cd -

wget http://downloads.sourceforge.net/project/expat/expat/2.2.0/expat-2.2.0.tar.bz2 -O - | tar xj
cd expat-2.2.0
./configure --prefix=/opt/prefix
make -j4
make install
cd -


wget http://ftp.gnu.org/gnu/gdbm/gdbm-1.12.tar.gz -O - | tar xz
cd gdbm-1.12
./configure --prefix=/opt/prefix
make -j4
make install
cd -


wget http://prdownloads.sourceforge.net/tcl/tcl8.6.6-src.tar.gz -O - | tar xz
cd tcl8.6.6/unix
./configure --prefix=/opt/prefix
make -j4
make install
cd -


wget http://prdownloads.sourceforge.net/tcl/tk8.6.6-src.tar.gz -O - | tar xz
cd tk8.6.6/unix
./configure --prefix=/opt/prefix
make -j4
make install
cd -


wget https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz -O - | tar xz 
cd Python-2.7.12
./configure --prefix=/opt/prefix/cpython-2.7
make -j4
make install
cd -


ln -sf /opt/prefix/lib/libtcl8.6.so /opt/prefix/lib/libtcl.so
ln -sf /opt/prefix/lib/libtk8.6.so /opt/prefix/lib/libtk.so

if [ -d /opt/prefix/lib64 ]; then
    cp /opt/prefix/lib64/* /opt/prefix/lib
fi

ln -sf /opt/prefix/lib/libexpat.so /opt/prefix/lib/libexpat.so.0
