#!/usr/bin/env python

bundle = ['sqlite3', 'ssl', 'crypto', 'ffi', 'expat', 'tcl', 'tk', 'gdbm', 'lzma', 'ncurses', 'panel', 'tinfo']

from os import chdir, mkdir, symlink
from os.path import dirname, relpath, join, samefile, exists, basename
from shutil import copy2, copytree
from sys import argv
from glob import glob
from subprocess import check_output, check_call


def get_deps(binary):
    deps = {}
    output = check_output(['ldd', binary])
    for line in output.splitlines():
        if not '=>' in line:
            continue
        line = line.strip()
        needed, path = line.split(' => ')
        if path == 'not found':
            print('Broken dependency in ' + binary)
        path = path.split(' ')[0]
        if not path:
            continue

        if needed[3:].split('.', 1)[0] not in bundle:
            continue

        deps[needed] = path
        deps.update(get_deps(path))

    return deps


def gather_deps(binaries):
    deps = {}
    for binary in binaries:
        deps.update(get_deps(binary))

    return deps


def symlink_deps(folder):
    symlinks = {}
    for lib in glob(join(folder, '*.so*')):
        if lib.endswith('.so'):
            continue

        lnkname, _, _ = lib.partition('.so.')
        lnkname += '.so'

        src = basename(lib)
        symlink(src, lnkname)
        symlinks[lnkname] = src
        print lnkname, src

    return symlinks


def copy_deps(deps):
    copied = {}

    for needed, path in deps.items():
        if exists('lib/' + needed) and samefile(path, 'lib/' + needed):
            continue

        copy2(path, 'lib/' + needed)
        copied[path] = 'lib/' + needed

    return copied


def rpath_binaries(binaries):
    rpaths = {}

    for binary in binaries:
        rpath = join('$ORIGIN', relpath('lib', dirname(binary)))
        check_call(['patchelf', '--set-rpath', rpath, binary])

        rpaths[binary] = rpath

    return rpaths


def strip(binaries):
    for binary in binaries:
        check_call(['chmod', 'a+w', binary])
        check_call(['strip', binary])
        check_call(['chmod', 'a-w', binary])


def main():
    binaries = ['bin/libpypy-c.so']
    binaries.extend(glob('lib_pypy/*_cffi.pypy*.so'))
    binaries.extend(glob('lib_pypy/_tkinter/*_cffi.pypy*.so'))

    deps = gather_deps(binaries)

    copied = copy_deps(deps)

    for path, item in copied.items():
        print('Copied {0} to {1}'.format(path, item))

    binaries.extend(copied.values())

    rpaths = rpath_binaries(binaries)
    for binary, rpath in rpaths.items():
        print('Set RPATH of {0} to {1}'.format(binary, rpath))

    strip(copied.values())
   
    symlink_deps('lib')

    check_call('cp -Lr /opt/prefix/include/* include', shell=True)

    return deps


if __name__ == '__main__':
    chdir(argv[1])

    try:
        mkdir('lib')
    except OSError:
        pass

    main()

    # tcl/tk library
    copytree('/opt/prefix/lib/tcl8.6', 'lib/tcl')
    copytree('/opt/prefix/lib/tk8.6', 'lib/tk')
    check_call(['patch', 'lib_pypy/_tkinter/app.py', '/src/_tkinter_app.py.patch'])
    if exists('lib-python/3'):
        check_call(['patch', 'lib-python/3/subprocess.py', '/src/subprocess3.py.patch'])
        check_call(['patch', 'lib-python/3/distutils/sysconfig_pypy.py', '/src/sysconfig_pypy.py.patch'])
    else:
        check_call(['patch', 'lib-python/2.7/subprocess.py', '/src/subprocess.py.patch'])
        check_call(['patch', 'lib-python/2.7/distutils/sysconfig_pypy.py', '/src/sysconfig_pypy.py.patch'])
