#!/bin/bash

set -e

REVISION=$1

export PATH=/opt/prefix/cpython-2.7/bin:$PATH

env

INPUTNAME=`find pypy-$REVISION -name "pypy*-c"`
NAME=`$INPUTNAME version.py`
echo using $NAME


BINNAME=pypy
if [[ $NAME == pypy3* ]]; then
    BINNAME=${NAME:0:7}
fi
echo binname $BINNAME


cd pypy-$REVISION
python pypy/tool/release/package.py --rename_pypy_c $BINNAME --archive-name pypy-$REVISION --targetdir /src --override_pypy_c ./../$INPUTNAME
cd -

rm -rf pypy-pack-$REVISION
mkdir pypy-pack-$REVISION

tar -C pypy-pack-$REVISION --strip-components=1 -xjf pypy-$REVISION.tar.bz2
if [[ $NAME == pypy3* ]]; then
    cd pypy-pack-$REVISION/bin
    ln -s $BINNAME pypy
    ln -s $BINNAME pypy3
    cd -
fi
./make_portable pypy-pack-$REVISION

cd pypy-pack-$REVISION/lib
ln -s libssl* libssl.so
ln -s libcrypto* libcrypto.so
cd -

mkdir pypy-pack-$REVISION/virtualenv_support
cd pypy-pack-$REVISION/virtualenv_support

wget https://raw.githubusercontent.com/pypa/virtualenv/16.1.0/src/virtualenv.py
wget https://github.com/pypa/virtualenv/raw/16.1.0/src/virtualenv_support/pip-18.1-py2.py3-none-any.whl
wget https://github.com/pypa/virtualenv/raw/16.1.0/src/virtualenv_support/setuptools-40.5.0-py2.py3-none-any.whl
wget https://github.com/pypa/virtualenv/raw/16.1.0/src/virtualenv_support/wheel-0.32.2-py2.py3-none-any.whl

cd -


if [[ $NAME != pypy3* ]]; then
  cd pypy-pack-$REVISION/lib-python/2.7
else
  cd pypy-pack-$REVISION/lib-python/3
fi
wget https://raw.githubusercontent.com/certifi/python-certifi/master/certifi/cacert.pem
cd -

cp /src/virtualenv-pypy pypy-pack-$REVISION/bin/virtualenv-pypy

rm -rf $NAME
mv pypy-pack-$REVISION $NAME

# clean __pycache__
find ./${NAME} -name "__pycache__" | xargs rm -rf >/dev/null 2>&1

rm -f ${NAME}.tar.bz2
tar -cjf ${NAME}.tar.bz2 $NAME

md5sum ${NAME}.tar.bz2
sha1sum ${NAME}.tar.bz2
sha256sum ${NAME}.tar.bz2
