#!/bin/bash

set -e

if [[ $ABI == 32 ]]; then
    PYPY_PATH=/opt/pypy-i686/bin
else
    PYPY_PATH=/opt/pypy-x86_64/bin
fi

if [[ $ABI == "32" ]]; then
    export CFLAGS="-m32 $CFLAGS"
    export CPPFLAGS=$CFLAGS
    export LDFLAGS="-m32 $LDFLAGS"
fi

export PATH=/opt/prefix/cpython-2.7/bin:$PATH

env

cd pypy
python pypy/tool/release/package.py --rename_pypy_c pypy --archive-name pypy --targetdir /src --override_pypy_c ./pypy-c
cd -

rm -rf pypy-pack
mkdir pypy-pack

tar -C pypy-pack --strip-components=1 -xjf pypy.tar.bz2
./make_portable pypy-pack

mkdir pypy-pack/virtualenv_support
cd pypy-pack/virtualenv_support

wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv.py
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/argparse-1.3.0-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/pip-7.0.1-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/setuptools-16.0-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/wheel-0.24.0-py2.py3-none-any.whl

cd -

cp /src/virtualenv-pypy pypy-pack/bin/virtualenv-pypy

NAME=`pypy/pypy-c version.py`
echo using $NAME

rm -rf $NAME
mv pypy-pack $NAME
rm -f ${NAME}.tar.bz2
tar -cjf ${NAME}.tar.bz2 $NAME
