#!/bin/bash

set -e

if [[ $ABI == "32" ]]; then
    export CFLAGS="-m32 $CFLAGS"
    export CPPFLAGS=$CFLAGS
    export LDFLAGS="-m32 $LDFLAGS"
fi

export PATH=/opt/prefix/cpython-2.7/bin:$PATH

env

cd pypy
./pypy-c pypy/tool/release/package.py --rename_pypy_c pypy --archive-name pypy --targetdir /src --override_pypy_c ./pypy-c
cd -

rm -rf pypy-pack
mkdir pypy-pack

tar -C pypy-pack --strip-components=1 -xjf pypy.tar.bz2
./make_portable pypy-pack

mkdir pypy-pack/virtualenv_support
cd pypy-pack/virtualenv_support

wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv.py
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/argparse-1.4.0-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/pip-8.1.1-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/setuptools-20.3-py2.py3-none-any.whl
wget --no-check-certificate https://github.com/pypa/virtualenv/raw/master/virtualenv_support/wheel-0.29.0-py2.py3-none-any.whl

cd -

cp /src/virtualenv-pypy pypy-pack/bin/virtualenv-pypy

NAME=`pypy/pypy-c version.py`
echo using $NAME

rm -rf $NAME
mv pypy-pack $NAME
rm -f ${NAME}.tar.bz2
tar -cjf ${NAME}.tar.bz2 $NAME

md5sum ${NAME}.tar.bz2
sha1sum ${NAME}.tar.bz2
sha256sum ${NAME}.tar.bz2
