#!/usr/bin/env python

"""This is a trampoline file to make it work on Python 2.4"""

from os.path import realpath, join, dirname
from subprocess import call
from sys import argv

here = dirname(realpath(__file__))
pypy = join(here, 'pypy')
virtualenv = join(here, '../virtualenv/virtualenv.py')

call([pypy, virtualenv] + argv[1:])
