FROM centos:centos6

RUN yum install -y wget setarch make bzip2-devel bzip2-devel.i686 zlib-devel zlib-devel.i686 glibc-devel glibc-devel.i686 libX11-devel libX11-devel.i686 libXt-devel libXt-devel.i686 patch expat.i686 expat libXft-devel libXft-devel.i686

RUN wget https://github.com/squeaky-pl/centos-devtools/releases/download/6.3/gcc-6.3.0-binutils-2.27-x86_64.tar.bz2 -O - | tar -C / -xj
